-- ============================================================================
-- Script: create_ds_admin_prerequisites.sql
-- Description: Create Data Safe profile prerequisites
-- ============================================================================

WHENEVER SQLERROR EXIT FAILURE

SET ECHO ON
SET TERMOUT ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 160 PAGESIZE 200
SET FEEDBACK OFF
SET VERIFY OFF

DEFINE _ds_profile = 'DS_USER_PROFILE'
COLUMN 1 NEW_VALUE 1 NOPRINT
SELECT '' "1" FROM dual WHERE ROWNUM = 0;
DEFINE ds_profile = &1 &_ds_profile

PROMPT Ensuring profile &&ds_profile exists with CIS-based limits

DECLARE
	l_count NUMBER := 0;
	l_profile VARCHAR2(128) := UPPER('&&ds_profile');
BEGIN
	SELECT COUNT(*)
	  INTO l_count
	  FROM dba_profiles
	 WHERE profile = l_profile;

	IF l_count = 0 THEN
		EXECUTE IMMEDIATE 'CREATE PROFILE ' || l_profile || ' LIMIT'
			|| ' SESSIONS_PER_USER UNLIMITED'
			|| ' FAILED_LOGIN_ATTEMPTS 5'
			|| ' PASSWORD_REUSE_MAX 5'
			|| ' PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION'
			|| ' COMPOSITE_LIMIT UNLIMITED'
			|| ' CPU_PER_SESSION UNLIMITED'
			|| ' CPU_PER_CALL UNLIMITED'
			|| ' LOGICAL_READS_PER_SESSION UNLIMITED'
			|| ' LOGICAL_READS_PER_CALL UNLIMITED'
			|| ' IDLE_TIME UNLIMITED'
			|| ' CONNECT_TIME UNLIMITED'
			|| ' PRIVATE_SGA UNLIMITED'
			|| ' PASSWORD_LIFE_TIME 31536000/86400'
			|| ' PASSWORD_REUSE_TIME 69120000/86400'
			|| ' PASSWORD_LOCK_TIME 299/86400'
			|| ' PASSWORD_GRACE_TIME DEFAULT'
			|| ' INACTIVE_ACCOUNT_TIME DEFAULT'
			|| ' PASSWORD_ROLLOVER_TIME 864000/86400';
		DBMS_OUTPUT.PUT_LINE('Created profile ' || l_profile);
	ELSE
		EXECUTE IMMEDIATE 'ALTER PROFILE ' || l_profile || ' LIMIT'
            || ' SESSIONS_PER_USER UNLIMITED'
			|| ' FAILED_LOGIN_ATTEMPTS 5'
			|| ' PASSWORD_REUSE_MAX 5'
			|| ' PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION'
			|| ' COMPOSITE_LIMIT UNLIMITED'
			|| ' CPU_PER_SESSION UNLIMITED'
			|| ' CPU_PER_CALL UNLIMITED'
			|| ' LOGICAL_READS_PER_SESSION UNLIMITED'
			|| ' LOGICAL_READS_PER_CALL UNLIMITED'
			|| ' IDLE_TIME UNLIMITED'
			|| ' CONNECT_TIME UNLIMITED'
			|| ' PRIVATE_SGA UNLIMITED'
			|| ' PASSWORD_LIFE_TIME 31536000/86400'
			|| ' PASSWORD_REUSE_TIME 69120000/86400'
			|| ' PASSWORD_LOCK_TIME 299/86400'
			|| ' PASSWORD_GRACE_TIME DEFAULT'
			|| ' INACTIVE_ACCOUNT_TIME DEFAULT'
			|| ' PASSWORD_ROLLOVER_TIME 864000/86400';
		DBMS_OUTPUT.PUT_LINE('Updated profile ' || l_profile);
	END IF;
END;
/

EXIT;
