-- ============================================================================
-- Script: create_ds_admin_prerequisites.sql
-- Description: Create Data Safe profile prerequisites
-- ============================================================================

WHENEVER SQLERROR EXIT FAILURE

SET ECHO ON
SET TERMOUT ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 160 PAGESIZE 200

PROMPT Ensuring profile DS_USER_PROFILE exists with CIS-based limits

DECLARE
	l_count NUMBER := 0;
BEGIN
	SELECT COUNT(*)
	  INTO l_count
	  FROM dba_profiles
	 WHERE profile = 'DS_USER_PROFILE';

	IF l_count = 0 THEN
		EXECUTE IMMEDIATE 'CREATE PROFILE DS_USER_PROFILE LIMIT'
			|| ' SESSIONS_PER_USER 10'
			|| ' FAILED_LOGIN_ATTEMPTS 5'
			|| ' PASSWORD_REUSE_MAX 20'
			|| ' PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION'
			|| ' COMPOSITE_LIMIT DEFAULT'
			|| ' CPU_PER_SESSION DEFAULT'
			|| ' CPU_PER_CALL DEFAULT'
			|| ' LOGICAL_READS_PER_SESSION DEFAULT'
			|| ' LOGICAL_READS_PER_CALL DEFAULT'
			|| ' IDLE_TIME DEFAULT'
			|| ' CONNECT_TIME DEFAULT'
			|| ' PRIVATE_SGA DEFAULT'
			|| ' PASSWORD_LIFE_TIME UNLIMITED'
			|| ' PASSWORD_REUSE_TIME 365'
			|| ' PASSWORD_LOCK_TIME 1'
			|| ' PASSWORD_GRACE_TIME 5'
			|| ' INACTIVE_ACCOUNT_TIME 120'
			|| ' PASSWORD_ROLLOVER_TIME DEFAULT';
		DBMS_OUTPUT.PUT_LINE('Created profile DS_USER_PROFILE');
	ELSE
		EXECUTE IMMEDIATE 'ALTER PROFILE DS_USER_PROFILE LIMIT'
			|| ' SESSIONS_PER_USER 10'
			|| ' FAILED_LOGIN_ATTEMPTS 5'
			|| ' PASSWORD_REUSE_MAX 20'
			|| ' PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION'
			|| ' COMPOSITE_LIMIT DEFAULT'
			|| ' CPU_PER_SESSION DEFAULT'
			|| ' CPU_PER_CALL DEFAULT'
			|| ' LOGICAL_READS_PER_SESSION DEFAULT'
			|| ' LOGICAL_READS_PER_CALL DEFAULT'
			|| ' IDLE_TIME DEFAULT'
			|| ' CONNECT_TIME DEFAULT'
			|| ' PRIVATE_SGA DEFAULT'
			|| ' PASSWORD_LIFE_TIME UNLIMITED'
			|| ' PASSWORD_REUSE_TIME 365'
			|| ' PASSWORD_LOCK_TIME 1'
			|| ' PASSWORD_GRACE_TIME 5'
			|| ' INACTIVE_ACCOUNT_TIME 120'
			|| ' PASSWORD_ROLLOVER_TIME DEFAULT';
		DBMS_OUTPUT.PUT_LINE('Updated profile DS_USER_PROFILE');
	END IF;
END;
/

EXIT;
